### ISSUE TITLE
Have a feature toggle to enable periodic refresh of tab every 15minutes ( or configurable durations)

### ISSUE THREAD

**Issue by TheMarvelousWhale** [get-artab/artab#2]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
It would be nice to have a feature to periodically refresh into new art work for the tab 

**Describe the solution you'd like**
Have a toggle to enable periodic refresh, with fixed duration interval / customizable interval 

**Describe alternatives you've considered**

**Additional context**

**Comment by theowenyoung** [comment]
Hi, we have an options for this, did this can help you for this?

![CleanShot 2024-12-19 at 01 49 02@2x](https://github.com/user-attachments/assets/e621f7e4-d664-4c55-8f38-1ec6518c4ea5)

**Comment by TheMarvelousWhale** [comment]
ahh i see, might have missed this out somehow. Thanks!
